/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/search` | `/search`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(mazi_tabuchi)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(mazi_tabuchi)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(mazi_tabuchi)'}/saved` | `/saved`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(mazi_tabuchi)'}/search` | `/search`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(mazi_tabuchi)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(mazi_tabuchi)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(mazi_tabuchi)'}/saved${`?${string}` | `#${string}` | ''}` | `/saved${`?${string}` | `#${string}` | ''}` | `${'/(mazi_tabuchi)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/saved` | `/saved`; params?: Router.UnknownInputParams; } | { pathname: `${'/(mazi_tabuchi)'}/search` | `/search`; params?: Router.UnknownInputParams; };
    }
  }
}
